version: 2.1
orbs:
  snyk: snyk/snyk@0.0.8
publish: &publish
  working_directory: ~/solar-budget
  docker:
    - image: circleci/node:10.13.0
  steps:
    - checkout
    - restore_cache:
        name: Restore yarn package cache
        key: v1-cache-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}-{{ arch }}
    - run:
        name: Install dependencies
        command: yarn install
    - run:
        name: Install Expo Cli
        command: yarn add --dev expo-cli
    - save_cache:
        name: Save yarn package cache
        paths:
          - ~/.cache/yarn
        key: v1-cache-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}-{{ arch }}
    - run:
        name: Login into Expo
        command: npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
    - run:
        name: Publish to Expo
        command: npx expo publish

jobs:
  build_and_test:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - restore_cache:
          name: Restore yarn package cache
          key: v1-cache-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}-{{ arch }}
      - run:
          name: Install dependencies
          command: yarn install
      - snyk/scan:
          fail-on-issues: false
          protect: true
          monitor-on-build: true
          severity-threshold: high
      - save_cache:
          name: Save yarn package cache
          paths:
            - ~/.cache/yarn
          key: v1-cache-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}-{{ arch }}
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Run linting
          command: yarn lint
      - run:
          name: Formatting code with Prettier
          command: yarn format

  publish_to_expo:
    <<: *publish

workflows:
  version: 2
  workflow:
    jobs:
      - build_and_test
      - publish_to_expo:
          requires:
            - build_and_test
          filters:
            branches:
              ignore: gh-pages
